services:
  jenkins:
    image: jenkins-image-jdk17:latest
    container_name: jenkins
    networks:
      - jenkins
      - shared-net
    ports:
      - "8080:8080"
      - "50000:50000"  # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  shared-net:
    external: true